# -*- coding: utf-8 -*-
"""ASCENSION Project (Phase 2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nxm775ppBfdhFlW9Wx-dLqu9aAJRk0qL
"""

pip install anthropic --quiet

import anthropic
import json
import time
from datetime import datetime
from IPython.display import display, HTML

try:
  API_KEY = userdata.get("ANTHROPIC_API_KEY")
except Exception:
  import os
  API_KEY = os.environ.get("ANTHROPIC_API_KEY", "AIzaSyCy9uzXNXJeKFGO2gjXbixv3BXbfrWLZwE")

client = anthropic.Anthropic(api_key=API_KEY)

THREAT_FEEDS = [
    {
        "id": "MX-2025-001",
        "source": "Foro Clandestino MX",
        "timestamp": "2025-04-25 02:14 UTC",
        "region": "México",
        "language": "es",
        "raw_text": (
            "Se vende acceso RDP a empresa financiera CDMX. Panel admin, "
            "500 equipos, sin AV activo. Precio: $800 USD crypto. "
            "Telegram: @sombra_red. Entrega inmediata. Solo BTC o XMR."
        ),
    },
    {
        "id": "ES-VE-2025-002",
        "source": "Canal Telegram ES-LATAM",
        "timestamp": "2025-04-25 01:58 UTC",
        "region": "España / Venezuela",
        "language": "es",
        "raw_text": (
            "Nuevo stealer para Android disponible. Roba credenciales bancarias, "
            "sesiones WhatsApp, fotos y contactos. Compatible con BBVA, Santander, "
            "Mercado Pago. Builder $200/mes. Probado en Venezuela y España. "
            "Soporte 24h. Muestra gratis."
        ),
    },
    {
        "id": "AR-2025-003",
        "source": "Foro Hacktivist AR",
        "timestamp": "2025-04-24 23:31 UTC",
        "region": "Argentina",
        "language": "es",
        "raw_text": (
            "Operación en curso contra Ministerio de Economía Argentina. "
            "Tenemos acceso a base de datos de contribuyentes. Exigimos transparencia "
            "fiscal o publicamos 2.3 millones de registros el viernes. "
            "No es bluff. #OpArgentina #Anonymous"
        ),
    },
    {
        "id": "CL-2025-004",
        "source": "Red Oscura CL",
        "timestamp": "2025-04-24 19:45 UTC",
        "region": "Chile",
        "language": "es",
        "raw_text": (
            "Nuevo grupo RaaS: 'Cóndor Negro'. Afiliados reciben 75% del rescate. "
            "Infraestructura en TOR, panel profesional. Ya comprometimos 3 clínicas "
            "en Santiago. Buscamos afiliados con acceso a redes corporativas. "
            "Contacto solo por I2P."
        ),
    },
    {
        "id": "LATAM-2025-005",
        "source": "Mercado Sombra LATAM",
        "timestamp": "2025-04-24 17:20 UTC",
        "region": "LATAM (multi-país)",
        "language": "es",
        "raw_text": (
            "Vendo base de datos empleados gobierno colombiano. 180,000 registros: "
            "nombre, cédula, cargo, email institucional, teléfono. "
            "Ideal para spear phishing o vishing. $500 negociables. "
            "Incluye muestra de 500 registros verificados."
        ),
    },
]

import random

MOCK_RESPONSES = [
    {
        "severity": "CRITICAL",
        "threat_type": "Initial Access Broker",
        "summary": "A threat actor is selling RDP access to a financial institution in Mexico City with admin-level privileges across 500 endpoints. The absence of active antivirus significantly lowers the barrier for follow-on ransomware or data exfiltration attacks.",
        "mitre_ttps": ["Remote Desktop Protocol", "Valid Accounts", "Exploit Public-Facing Application"],
        "targeted_sectors": ["Finance", "Banking"],
        "targeted_countries": ["Mexico"],
        "iocs": ["@sombra_red (Telegram)"],
        "threat_actor_profile": "Financially motivated broker, moderate sophistication, likely Mexico or Central America based. Operates via Telegram and accepts crypto only.",
        "analyst_actions": ["Block RDP exposure on perimeter firewalls", "Alert financial sector ISACs", "Monitor Telegram handle for further activity"],
        "intelligence_gaps": ["Unknown which specific financial institution is targeted", "Unclear if access is already monetized"],
        "confidence": "HIGH",
        "tlp": "TLP:RED"
    },
    {
        "severity": "HIGH",
        "threat_type": "Mobile Banking Trojan / Stealer-as-a-Service",
        "summary": "A Spanish-language actor is distributing an Android stealer targeting major Spanish and Latin American banks including BBVA and Santander. The builder model suggests a commercialized operation with ongoing development and customer support.",
        "mitre_ttps": ["Credential Dumping", "Input Capture", "Exfiltration Over C2 Channel"],
        "targeted_sectors": ["Banking", "Financial Services", "E-commerce"],
        "targeted_countries": ["Spain", "Venezuela"],
        "iocs": [],
        "threat_actor_profile": "Technically capable actor offering MaaS (Malware-as-a-Service). Bilingual support suggests established criminal operation targeting Ibero-American markets.",
        "analyst_actions": ["Alert BBVA and Santander threat intel teams", "Submit sample request to VirusTotal community", "Monitor for new Android APK drops"],
        "intelligence_gaps": ["C2 infrastructure not identified", "Distribution vector unknown"],
        "confidence": "MEDIUM",
        "tlp": "TLP:AMBER"
    },
    {
        "severity": "HIGH",
        "threat_type": "Hacktivist Data Extortion",
        "summary": "A hacktivist group claiming Anonymous affiliation is threatening to leak 2.3 million Argentine taxpayer records unless the Ministry of Economy complies with transparency demands. The Friday deadline creates urgency for incident response.",
        "mitre_ttps": ["Data Exfiltration", "Publicly Accessible Data", "Defacement"],
        "targeted_sectors": ["Government", "Public Sector"],
        "targeted_countries": ["Argentina"],
        "iocs": ["#OpArgentina"],
        "threat_actor_profile": "Ideologically motivated hacktivist, low-to-moderate sophistication. Likely a loosely organized group using Anonymous branding for legitimacy.",
        "analyst_actions": ["Notify Argentine CERT (CERT.ar) immediately", "Assess Ministry of Economy network for indicators of compromise", "Prepare public communications plan"],
        "intelligence_gaps": ["Actual data possession unverified", "Group identity and size unknown"],
        "confidence": "MEDIUM",
        "tlp": "TLP:AMBER"
    },
    {
        "severity": "CRITICAL",
        "threat_type": "Ransomware-as-a-Service (RaaS)",
        "summary": "A new RaaS group called 'Cóndor Negro' is actively recruiting affiliates and claims to have already compromised three Santiago healthcare facilities. The 75% affiliate payout is above market rate, suggesting aggressive expansion.",
        "mitre_ttps": ["Data Encrypted for Impact", "Inhibit System Recovery", "Phishing for Initial Access"],
        "targeted_sectors": ["Healthcare", "Critical Infrastructure"],
        "targeted_countries": ["Chile"],
        "iocs": ["Cóndor Negro (group name)", "I2P contact channel"],
        "threat_actor_profile": "Sophisticated financially motivated RaaS operator. Use of I2P over Tor suggests above-average operational security awareness.",
        "analyst_actions": ["Alert Chilean healthcare sector CISOs", "Share TTPs with CSIRT Chile", "Hunt for I2P-based C2 beaconing on healthcare networks"],
        "intelligence_gaps": ["Ransomware strain not yet identified", "Affiliate recruitment success rate unknown"],
        "confidence": "HIGH",
        "tlp": "TLP:RED"
    },
    {
        "severity": "HIGH",
        "threat_type": "Government PII Database Sale",
        "summary": "A threat actor is selling a database of 180,000 Colombian government employees including institutional emails and phone numbers. The data is explicitly marketed for spear phishing and vishing, indicating imminent social engineering campaigns.",
        "mitre_ttps": ["Phishing", "Spearphishing", "Valid Accounts"],
        "targeted_sectors": ["Government", "Public Administration"],
        "targeted_countries": ["Colombia"],
        "iocs": [],
        "threat_actor_profile": "Data broker with access to sensitive government records. Motivation is financial. May have insider access or have obtained data via prior breach.",
        "analyst_actions": ["Notify Colombian government CSIRT", "Advise targeted agencies to increase phishing awareness training", "Attempt to verify data authenticity via sample"],
        "intelligence_gaps": ["Original breach source unknown", "Whether data is already widely distributed is unclear"],
        "confidence": "HIGH",
        "tlp": "TLP:AMBER"
    },
]


def analyze_threat(feed_item: dict) -> dict:
    """Mock analysis — returns realistic fake intel without calling the API."""
    # Match mock response to feed order
    idx = int(feed_item["id"].split("-")[-1]) - 1
    intel = MOCK_RESPONSES[idx % len(MOCK_RESPONSES)].copy()
    intel["feed_id"] = feed_item["id"]
    intel["source"] = feed_item["source"]
    intel["region"] = feed_item["region"]
    intel["timestamp"] = feed_item["timestamp"]
    intel["raw_text"] = feed_item["raw_text"]
    return intel

SEVERITY_COLORS = {
    "CRITICAL": ("#ff2d55", "#2a0a10"),
    "HIGH":     ("#ff9f0a", "#2a1a00"),
    "MEDIUM":   ("#ffd60a", "#2a2200"),
    "LOW":      ("#30d158", "#0a1f10"),
}

TLP_COLORS = {
    "TLP:RED":   "#ff2d55",
    "TLP:AMBER": "#ff9f0a",
    "TLP:GREEN": "#30d158",
}


def render_intelligence_card(intel: dict) -> str:
    """Render a threat intelligence report as a styled HTML card for Colab."""

    sev = intel.get("severity", "MEDIUM")
    sev_color, sev_bg = SEVERITY_COLORS.get(sev, ("#ffd60a", "#2a2200"))
    tlp = intel.get("tlp", "TLP:AMBER")
    tlp_color = TLP_COLORS.get(tlp, "#ff9f0a")

    def pill(text, color="#aaa", bg="rgba(255,255,255,0.08)"):
        return (
            f'<span style="display:inline-block;padding:2px 10px;border-radius:20px;'
            f'font-size:11px;font-weight:600;background:{bg};color:{color};'
            f'border:1px solid {color}40;margin:2px;">{text}</span>'
        )

    def section(title, items):
        if not items:
            return ""
        if isinstance(items, list):
            content = "".join(f"<li style='margin:3px 0;color:#ccc;font-size:13px;'>{i}</li>" for i in items)
            content = f"<ul style='margin:6px 0 0 16px;padding:0;'>{content}</ul>"
        else:
            content = f"<p style='margin:6px 0 0;color:#ccc;font-size:13px;line-height:1.5;'>{items}</p>"
        return (
            f'<div style="margin-top:14px;">'
            f'<div style="font-size:10px;letter-spacing:0.12em;color:#666;font-weight:700;'
            f'text-transform:uppercase;margin-bottom:2px;">{title}</div>'
            f'{content}</div>'
        )

    ttps_pills = "".join(pill(t, "#bf5fff", "rgba(191,95,255,0.1)")
                         for t in intel.get("mitre_ttps", []))
    sector_pills = "".join(pill(s, "#5fb3ff", "rgba(95,179,255,0.1)")
                           for s in intel.get("targeted_sectors", []))
    country_pills = "".join(pill(c, "#30d158", "rgba(48,209,88,0.1)")
                            for c in intel.get("targeted_countries", []))
    ioc_pills = "".join(pill(i, "#ff9f0a", "rgba(255,159,10,0.1)")
                        for i in intel.get("iocs", []))

    html = f"""
    <div style="font-family:'Courier New',monospace;background:#0d0d0d;border:1px solid {sev_color}40;
                border-left:4px solid {sev_color};border-radius:8px;padding:20px;
                margin:12px 0;box-shadow:0 4px 24px rgba(0,0,0,0.5);">

      <!-- Header -->
      <div style="display:flex;justify-content:space-between;align-items:flex-start;flex-wrap:wrap;gap:8px;">
        <div>
          <div style="font-size:11px;color:#555;letter-spacing:0.15em;margin-bottom:4px;">
            {intel['feed_id']} · {intel['source']} · {intel['timestamp']}
          </div>
          <div style="font-size:16px;font-weight:700;color:#eee;">
            {intel.get('threat_type','Unknown Threat')}
          </div>
          <div style="font-size:12px;color:#888;margin-top:2px;">📍 {intel['region']}</div>
        </div>
        <div style="display:flex;flex-direction:column;align-items:flex-end;gap:6px;">
          <span style="padding:4px 14px;border-radius:4px;font-size:12px;font-weight:800;
                       letter-spacing:0.1em;background:{sev_bg};color:{sev_color};
                       border:1px solid {sev_color};">⚠ {sev}</span>
          <span style="font-size:11px;font-weight:700;color:{tlp_color};">{tlp}</span>
          <span style="font-size:11px;color:#555;">Confidence:
            <span style="color:#aaa;">{intel.get('confidence','MEDIUM')}</span>
          </span>
        </div>
      </div>

      <!-- Divider -->
      <div style="border-top:1px solid #222;margin:14px 0;"></div>

      <!-- Raw post -->
      <div style="background:#111;border-left:3px solid #333;padding:10px 14px;
                  border-radius:4px;font-size:12px;color:#777;line-height:1.6;
                  font-style:italic;">
        "{intel['raw_text']}"
      </div>

      {section("📋 Intelligence Summary", intel.get('summary',''))}
      {section("🎯 Targeted Sectors", None) if not intel.get('targeted_sectors') else
       '<div style="margin-top:14px;"><div style="font-size:10px;letter-spacing:0.12em;color:#666;font-weight:700;text-transform:uppercase;margin-bottom:6px;">🎯 Targeted Sectors</div>' + sector_pills + '</div>'}
      {('<div style="margin-top:14px;"><div style="font-size:10px;letter-spacing:0.12em;color:#666;font-weight:700;text-transform:uppercase;margin-bottom:6px;">🌎 Countries</div>' + country_pills + '</div>') if country_pills else ''}
      {('<div style="margin-top:14px;"><div style="font-size:10px;letter-spacing:0.12em;color:#666;font-weight:700;text-transform:uppercase;margin-bottom:6px;">⚔ MITRE ATT&CK TTPs</div>' + ttps_pills + '</div>') if ttps_pills else ''}
      {('<div style="margin-top:14px;"><div style="font-size:10px;letter-spacing:0.12em;color:#666;font-weight:700;text-transform:uppercase;margin-bottom:6px;">🔍 IOCs / Contact</div>' + ioc_pills + '</div>') if ioc_pills else ''}
      {section("🕵 Threat Actor Profile", intel.get('threat_actor_profile',''))}
      {section("✅ Recommended Analyst Actions", intel.get('analyst_actions',[]))}
      {section("❓ Intelligence Gaps", intel.get('intelligence_gaps',[]))}

    </div>
    """
    return html


def render_dashboard_header(total: int, critical: int, high: int) -> str:
    return f"""
    <div style="font-family:'Courier New',monospace;background:#050505;
                border:1px solid #1a1a1a;border-radius:8px;padding:24px;margin-bottom:8px;">
      <div style="color:#00ff64;font-size:22px;font-weight:700;letter-spacing:0.15em;
                  text-shadow:0 0 20px rgba(0,255,100,0.5);">
        ◈ CENTINELA OSINT
      </div>
      <div style="color:#444;font-size:11px;letter-spacing:0.3em;margin-top:4px;">
        SPANISH-LANGUAGE THREAT INTELLIGENCE MONITOR
      </div>
      <div style="display:flex;gap:24px;margin-top:16px;flex-wrap:wrap;">
        <div style="text-align:center;">
          <div style="font-size:28px;font-weight:700;color:#eee;">{total}</div>
          <div style="font-size:10px;color:#555;letter-spacing:0.1em;">TOTAL ANALYZED</div>
        </div>
        <div style="text-align:center;">
          <div style="font-size:28px;font-weight:700;color:#ff2d55;">{critical}</div>
          <div style="font-size:10px;color:#555;letter-spacing:0.1em;">CRITICAL</div>
        </div>
        <div style="text-align:center;">
          <div style="font-size:28px;font-weight:700;color:#ff9f0a;">{high}</div>
          <div style="font-size:10px;color:#555;letter-spacing:0.1em;">HIGH</div>
        </div>
        <div style="text-align:center;">
          <div style="font-size:28px;font-weight:700;color:#00ff64;">LIVE</div>
          <div style="font-size:10px;color:#555;letter-spacing:0.1em;">STATUS</div>
        </div>
      </div>
    </div>
    """

def run_centinela(feeds=None, max_feeds=5):
    """
    Main analysis pipeline.

    Args:
        feeds: list of feed dicts. Defaults to built-in THREAT_FEEDS.
        max_feeds: limit how many feeds to analyze (API cost control).
    """
    if feeds is None:
        feeds = THREAT_FEEDS

    feeds = feeds[:max_feeds]
    results = []

    print(f"[CENTINELA] Starting analysis of {len(feeds)} threat feed items...")
    print(f"[CENTINELA] Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n")

    for i, feed in enumerate(feeds):
        print(f"  [{i+1}/{len(feeds)}] Analyzing {feed['id']} ({feed['source']})...", end=" ")
        try:
            intel = analyze_threat(feed)
            results.append(intel)
            print(f"✓ {intel.get('severity','?')} severity")
        except Exception as e:
            print(f"✗ Error: {e}")

        # Rate limit courtesy pause
        if i < len(feeds) - 1:
            time.sleep(1)

    # Tally severity counts
    critical = sum(1 for r in results if r.get("severity") == "CRITICAL")
    high = sum(1 for r in results if r.get("severity") == "HIGH")

    # Render dashboard
    print("\n[CENTINELA] Rendering intelligence dashboard...\n")
    display(HTML(render_dashboard_header(len(results), critical, high)))

    # Sort: CRITICAL first, then HIGH, etc.
    order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    results.sort(key=lambda r: order.get(r.get("severity", "LOW"), 9))

    for intel in results:
        display(HTML(render_intelligence_card(intel)))

    print(f"\n[CENTINELA] Analysis complete. {len(results)} reports generated.")
    return results

if __name__ == "__main__":
    # Analyze all 5 simulated feeds
    intelligence_reports = run_centinela(max_feeds=5)

    # Optional: export to JSON
    with open("centinela_output.json", "w", encoding="utf-8") as f:
        json.dump(intelligence_reports, f, ensure_ascii=False, indent=2)
    print("\n[CENTINELA] Reports saved to centinela_output.json")

from google.colab import userdata
key = userdata.get("ANTHROPIC_API_KEY")
print(f"Key found: {key is not None}")
print(f"Key preview: {key[:10]}..." if key else "NO KEY FOUND")